namespace OrgPalThreeDemo.Peripherals.LufftShm31
{
    public enum DeviceErrorCode
    {
        LaserSignalTooWeak = 15,
        LaserSignalTooStrong,
        LaserBackgroundLightLevelTooStrong,
        LaserMeasurementDisturbed,
        LaserTimeoutOff,
        LaserCommsInterface,
        LaserCommsResponse,
        LaserTemperatureTooLow,
        LaserTemperatureTooHigh,
        HardwareEepromChecksumIncorrect = 31,
        LaserEepromChecksumIncorrect,
        LaserAPD = 51,
        LaserCurrent,
        MathematicsDivisionByZero,
        LaserHardware,
        GeneralHardware,
        GeneralHardwareInterface = 61,
        SerialParity,
        SerialOverflow,
        SerialFraming,
        EvaluationFailure,
        MeasurementCancelled,
        TelegramNotAvailable,
        // Evaluation Routine:
        ReadSettingsDataFailed = 70,
        ReadLaserDataFailed,
        ReadLaserTemperatureFailed,
        ReadBlockTemperatureFailed,
        ReadOutsideTemperatureFailed,
        ReadLaserDistanceFailed,
        GyroVectorLength,
        ReferenceAngleInvalid,
        SignalDivision,
        SignalTooSmall,
        SignalTooLarge,
        NoAngleCorrection,
        ChannelAverageCountOverflow,
        RingBufferInitialization = 83,
    }
}
