name: Build

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:


jobs: 
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: nanoframework/nanobuild@v1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      
      - name: Install NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild ${{env.SOLUTION_FILE_PATH}} /verbosity:normal /p:Configuration=Release /nologo
